### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/dataset-knowledge-graph#24]
- [x] #11
- [x] #3
- [x] #4
- [x] #19 
- [x] Optimise pipeline speed by checking SPARQL endpoint availability before running other analyzers
- [ ] #23
- [x] #1 
- [x] #5
- [x] #10
- [x] Log SPARQL endpoint uptime and response times
- [x] #6 
- [x] Expand tests and coverage.
- [ ] #55
